### ISSUE TITLE
Смысл троеточия и способ построения композиций

### ISSUE THREAD

**Issue by ulysses4ever** [SimplePrutik/Random#8]
Детально пояснить почему работает или не работает вот это:

```
sum2 <- function (...)
{
    sqrt(sum((function (x) x * x))) #did point hit the cicle or not
}
```

**Comment by SimplePrutik** [comment]
как оказалось, ничего криминального не произошло, просто Вы тогда, видимо, не сохранили файл, и он работал по старой версии с функциями, потому что я повторил эксперимент и R на меня выругался

троеточие, как я и говорил, служит для неопределенного количества аргументов, также для аргументов для подфункций

ну а функции я заменил на такую лямбду

```
function(x) sqrt(sum(x*x)))
```
